### PR TITLE
complete page revamp

### PR DESCRIPTION
**Pull request by Dakkers**
I used Bootstrap for the functionality because it makes life easy. please let me know if you think this is good enough.

### CODE REVIEW

**Comment by obiot** [comment]
oh great, so fast !

could you however put it somewhere online, or re-do the pull request on the "revamp" branch I created ? that will allow to iterate over it and only publish the final version on the main/gh-pages branch when finished ?

**Comment by parasyte** [comment]
Nice! This is really an excellent start.

@StDako Two comments:
1. Can we make the side-nav sticky? I hate sticky navigation menus on normal websites, but for documentation, it's invaluable.
2. Use the [`:target` pseudo-selector](http://css-tricks.com/on-target/) to highlight the section that the nav menu jumps to. You can also go extra-snazzy and change the jumping behavior to smooth-scroll with a tiny bit of JavaScript (uses jQuery): https://github.com/parasyte/node-capstone/blob/master/views/js/app.js#L12-L24

@obiot Click the link that says "command line" within the little "Merge Pull Request" info box, and it will give you instructions on how you can create a new local branch and merge these changes into it, which is great for testing locally. Apart from that, the changes are already in a gh-pages branch on @StDako's github, so you can use that directly: http://stdako.github.io/tutorial-platformer/

You can also rebase it on top of the `revamp` branch, but then you won't get the auto gh-pages magic (as it should be rebased into a new branch).

**Comment by Dakkers** [comment]
@parasyte I got the first part down with a sticky header as well, otherwise I would have to involve jQuery, which would be nice to leave out as a dependency for the sake of not having more dependencies. I forgot to do the `:target` stuff before committing so I'll do that now.

**Comment by parasyte** [comment]
Brilliant! We need the same [`offset-anchor`](https://github.com/StDako/tutorial-platformer/commit/92923a6094d5c543cea8411e17472935e6950f6d#diff-f0fe19c690c52e0eb9fc55ab493e6e98R41) trick for the documentation: http://melonjs.github.io/docs/me.CanvasRenderer.html#drawShape (and :target, of course)

**Comment by obiot** [comment]
the new page looks great, and it's actually finished :p

for header, could you maybe make it a big smaller like the one we use for the documentation, and also match with the green color ?
http://melonjs.github.io/docs/

see here below for the logo :
https://github.com/melonjs/melonJS/blob/master/tasks/jsdoc-template/template/static/images/melon.png

**Comment by Dakkers** [comment]
do you still want the "Fork me on GitHub" ribbon as well?

**Comment by obiot** [comment]
no maybe not on the tutorial page :)

**Comment by Dakkers** [comment]
okay, sure thing. also, what dropdown menus do you want on the tutorial page?

**Comment by Dakkers** [comment]
err, links, not necessarily dropdowns.

**Comment by obiot** [comment]
I think everything useful is there already ? 

Maybe a link back to our homepage and the forum. although the latter could be added in the introduction in case people need to seek for help :)

**Comment by Dakkers** [comment]
I changed the navbar and got the `:target` selector working, things look pretty decent, although I personally think it would look better if it was a full-width container. also I'm not sure if you guys like the color of the transition or not, I just picked some light green I saw.

**Comment by obiot** [comment]
hi guys, sorry i did not have the time to follow on this one since a couple of days ! 

seems like we are done here anyway, and that we can merge this into the main gh-pages branch ?

**Comment by parasyte** [comment]
Yes, please!

**Comment by obiot** [comment]
awesome ! thank you again @StDako for this !

**Pull request merged**
