### PR TITLE
Update Code to ES6 + Latest Version of MelonJS

### PR DESCRIPTION
**Pull request by kkeiper1103**
This pull request updates the example code to use both ES6 and MelonJS 10.

### CODE REVIEW

**Comment by kkeiper1103** [comment]
Also, not sure where to put this, but I thought it might be good to show the tutorial platformer as built from the es6-boilerplate template. That repository can be found here. Would you want ownership of the repository or do you think this wouldn't be beneficial to new learners?

https://github.com/kkeiper1103/tutorial-platformer-from-boilerplate

**Comment by obiot** [comment]
> Also, not sure where to put this, but I thought it might be good to show the tutorial platformer as built from the es6-boilerplate template. That repository can be found here. Would you want ownership of the repository or do you think this wouldn't be beneficial to new learners?
> 
> https://github.com/kkeiper1103/tutorial-platformer-from-boilerplate

you mean this pull request here does not include the es6 boilerplate ?

I will look at it today, and actually probably then include the boilerplate, as it just makes sense as well in my opinion

thank you so much again for this !

**Comment by kkeiper1103** [comment]
the code does not start from the es6-boilerplate, as I simply cloned the repository and rewrote the code until it worked in ES6. After I got done, I wanted to see how it would look with the es6-boilerplate as a starting point, so that's the the second repository is. 

The more I think about it, the more I think I I should do some more work on this to make it start from es6. I think I'll start on another branch that builds from the es6-boilerplate instead of the old boilerplate. That would make more sense.

**Comment by obiot** [comment]
Sorry, at the end I did not have the time to look at it (promise i’ll do tomorrow). Anyway this is already tremendous work and a great start. Using the es6 boilerplate can be left at the initiative of the one going through the tutorial. And after all using the es6 boilerplate does not make it easy to show intermediate steps (but maybe those parts should be removed and just show the final result ?)

**Comment by obiot** [comment]
@kkeiper1103 Hi, so I merged the pull request, and went through the tutorial. There is definitely something to do with the boilerplate, as now it mixes both the old boilerplate with ES6 syntax and class which won't actually work.

So I was thinking (tell me what you think) :
- make the tutorial start over from the new es6-boilerplate (at least makes it a suggestion, and refer to the boilerplate documentation on [how to use it](https://github.com/melonjs/es6-boilerplate/blob/main/README.md))
- remove all running intermediate steps (it's a mess to keep up-dated), and only provide a screenshot per step.
- the final or complete tutorial source code and example are still provided, but then in the es6 boilerplate format.

**Pull request merged**
