### PR TITLE
Add missing 'metatiles32x32' reference to game resources files

### PR DESCRIPTION
**Pull request by robatron**
Add missing 'metatiles32x32' reference to game resources files in tutorial and tutorial support files to fix the "melonJS: 'metatiles32x32' file for tileset 'metatiles32x32' not found!" error message

### CODE REVIEW

**Comment by obiot** [comment]
Hi, this was actually made on purpose, as there is no need to load the metatiles asset, if ones does not display it through the debug panel, and moreover this is the only asset for which melonjs will not throw an exception if missing (but only a warning).

**Comment by obiot** [comment]
changed of mind, as this is actually maybe a better option to add this by default to avoid confusing people :p

as without this asset being loaded, the "display collision layer" in the debug panel won't be functional, and new user might not then understand why !

thank you very much !
Olivier,

**Comment by robatron** [comment]
I forgot to respond, but I was going to say something to the same effect, i.e., the error messages would at least be confusing to newbs like myself ;-)

Thanks!

~Rob

**Comment by parasyte** [comment]
@obiot We should also apply this patch to all examples in the main repo!

**Pull request merged**
