### PR TITLE
Added information for creating an Entity

### PR DESCRIPTION
**Pull request by travispaul**
I got stuck trying to add an Entity in Tiled and saw that I wasn't alone (https://github.com/melonjs/melonJS/issues/22)
So I added a small note and fixed a few minor typos that I noticed.
Great tutorial BTW, I just got really confused about the Entity.

### CODE REVIEW

**Comment by parasyte** [comment]
@TravisPaul Thanks for this! We'll merge it after the 0.9.7 release. We have a branch for 0.9.7 where all of the work has been done since version 0.9.6. (Which will be merged separately for release, as well!)

**Comment by travispaul** [comment]
@parasyte Sounds good to me.

**Comment by obiot** [comment]
Hi, thank you very much.

However I won't actually merge this one as such, as I already did the same improvement on the pending 0.9.7 branch, and i don't want to risk an additional merge conflict.... (i kind of suck in managing conflicts with GitHub)

I will however carefully reuse (copy/pasta) all the improvements you just proposed :)

thank you very much again !

**Comment by travispaul** [comment]
@obiot after parasyte mentioned the 0.9.7 branch I figured that this pull request might not merge very well. If you can still use some of it that's great, if not no biggie.

**Pull request closed without merging**
